#!/usr/bin/env python
# encoding: utf-8
### BEGIN INIT INFO
# Provides:          tightvncserver
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start/stop tightvncserver
### END INIT INFO

import os
import argparse
import sys
import subprocess


parser = argparse.ArgumentParser(description="Start the vnc server")
parser.add_argument("command")
parser.add_argument("-u", "--user", default="pi")
parser.add_argument("-s", "--screen", default="760x400")
parser.add_argument("-n", "--number", default="1")

args = parser.parse_args(sys.argv[1:])

os.environ["USER"] = args.user
os.chdir("/home/%s" % args.user)

if args.command == "start":
    status = subprocess.check_call([
        "tightvncserver", "-geometry",
        args.screen, ":%s" % args.number])

elif args.command == "stop":
    status = subprocess.check_call([
        "tightvncserver", "-kill",
        ":%s" % args.number])

exit(status)
